config/routes.rb
Rails.application.routes.draw do

    resources :enc_contactos do
        resources :contactos
    end

    root 'enc_contactos#index'

end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :enc_contacto
    validates :cedula, presence: true,
                       length: { is: 11 },
                       format: { with: /\A[0-9]+\z/,
                                 message: "solo permite numeros" },
                       uniqueness: true

    validates :sexo, inclusion: { in: %w(M F),message: "%{value} is not a valid size" },
    length: { is: 1 }

    #validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/,
    #message: "only allows letters" }

    #validates :size, inclusion: { in: %w(small medium large),
    #message: "%{value} is not a valid size" }



  #validates :name, length: { minimum: 2 }
  #validates :bio, length: { maximum: 500 }
  #validates :password, length: { in: 6..20 }
  #validates :registration_number, length: { is: 6 }

    validates :mesa, presence: true,
                    length: { is: 4 }
end

app/models/enc_contacto.rb
class EncContacto < ActiveRecord::Base
     has_many :contactos, dependent: :destroy
    validates :cedula, presence: true,
                       length: { is: 11 },
                       format: { with: /\A[0-9]+\z/,
                                 message: "solo permite numeros" },
                       uniqueness: true



    validates :mesa, presence: true,
                    length: { is: 4 }

    #accept_nested_attributes_for :contactos, :allow_destroy => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    add_flash_types :error, :another_custom_type
end

app/controllers/contactos_controller.rb
class ContactosController < ApplicationController
    http_basic_authenticate_with name: "difo", password: "difo", only: :destroy
 def index

  end

 # GET /enc_contactos/new
  def new
        @enc_contacto = EncContacto.find(params[:enc_contacto_id])
      @contacto = @enc_contacto.contactos.new
  end

  def edit
      @contacto = Contacto.find(params[:id])
      @enc_contacto = EncContacto.find(params[:enc_contacto_id])
  end


    def update
        @contacto = Contacto.find(params[:id])
        @enc_contacto = EncContacto.find(params[:enc_contacto_id])
        respond_to do |format|
          if @contacto.update(contacto_params)
              format.html { redirect_to @enc_contacto, notice: 'Contacto was successfully updated.' }
              format.json { render :show, status: :ok, location: @enc_contacto }
          else
            format.html { render :edit }
              format.json { render json: @enc_contacto.errors, status: :unprocessable_entity }
          end
        end
      end



    def create
        @enc_contacto = EncContacto.find(params[:enc_contacto_id])
        @contacto = @enc_contacto.contactos.create(contacto_params)

    respond_to do |format|
      if @contacto.save
          format.html { redirect_to "/enc_contactos/#{@enc_contacto.id}/contactos/new", notice: 'Contacto was successfully created. Nombre: '+@contacto.nombre+' Cedula: '+@contacto.cedula }
        #format.json { render :show, status: :created, location: @contacto }
      else
        format.html { render :new }
        #format.json { render json: @contacto.errors, status: :unprocessable_entity }
      end
    end


  end

    def destroy

    @contacto = Contacto.find(params[:id])
    @enc_contacto = EncContacto.find(params[:enc_contacto_id])
    @contacto.destroy
    respond_to do |format|
        format.html { redirect_to enc_contacto_path(@enc_contacto), notice: 'Contacto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def contacto_params
      params.require(:contacto).permit(
      :nombre,
      :apellido,
      :cedula,
      :celular,
      :telefono,
      :mesa,
      :paraje,
      :email,
      :edad,
      :sexo,
      :fecha_ultimo_contacto,
      :intesion
          )
    end
end

app/controllers/enc_contactos_controller.rb
class EncContactosController < ApplicationController
  before_action :set_enc_contacto, only: [:show, :edit, :update, :destroy]
    http_basic_authenticate_with name: "difo", password: "difo", only: :destroy
  # GET /enc_contactos
  # GET /enc_contactos.json
  def index
    @enc_contactos = EncContacto.all
  end

  # GET /enc_contactos/1
  # GET /enc_contactos/1.json
  def show
        @contacto= @enc_contacto.contactos.build
  end

  # GET /enc_contactos/new
  def new
    @enc_contacto = EncContacto.new
  end

  # GET /enc_contactos/1/edit
  def edit
  end

  # POST /enc_contactos
  # POST /enc_contactos.json
  def create
    @enc_contacto = EncContacto.new(enc_contacto_params)

    respond_to do |format|
      if @enc_contacto.save
        format.html { redirect_to @enc_contacto, notice: 'Enc contacto was successfully created.' }
        format.json { render :show, status: :created, location: @enc_contacto }
      else
        format.html { render :new }
        format.json { render json: @enc_contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enc_contactos/1
  # PATCH/PUT /enc_contactos/1.json
  def update
    respond_to do |format|
      if @enc_contacto.update(enc_contacto_params)
        format.html { redirect_to @enc_contacto, notice: 'Enc contacto was successfully updated.' }
        format.json { render :show, status: :ok, location: @enc_contacto }
      else
        format.html { render :edit }
        format.json { render json: @enc_contacto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enc_contactos/1
  # DELETE /enc_contactos/1.json
  def destroy
   #@enc_contacto.contactos.each do |contacto|
    #   contacto.destroy

   #end
    @enc_contacto.destroy

    respond_to do |format|
      format.html { redirect_to enc_contactos_url, notice: 'Enc contacto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enc_contacto
      @enc_contacto = EncContacto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enc_contacto_params
      params.require(:enc_contacto).permit(:nombre, :apellido, :cedula, :celular, :telefono, :mesa, :paraje)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/enc_contactos_helper.rb
module EncContactosHelper




end

app/views/contactos/edit.html.erb
<h3>Editar un Contacto</h3>

<%= form_for(@contacto, url: "/enc_contactos/#{@enc_contacto.id}/contactos/#{@contacto.id}" , html: {method: "patch"}) do |f| %>

<table>
  <thead>
     <tr>
 <td>

<% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> prohibited this contacto from being saved:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   </td></tr>
</thead>
 <tbody>

     <tr>
              <td>
   <div class="field">
   <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

         </td>
     </tr>

    <tr>
              <td>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>

                   </td>
     </tr>

     <tr>
              <td>
  <div class="field">
    <%= f.label :cedula %><br>
    <%= f.text_field :cedula %>
  </div>
                   </td>
     </tr>

     <tr>
              <td>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>

                  </td>
     </tr>

     <tr>
              <td>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>

                   </td>
     </tr>

  <tr>
              <td>
  <div class="field">
    <%= f.label :mesa %><br>
     <%= f.select :mesa, ['0069', '069A','0252','0307','0226','0325','0073','0074','0077','0075','0076','0271','0072','0225','0306','065A','0065','0070','0224','0308','0067','0068','068A','0066','0071','0079','0078','0081','080A','0080','0082','0083','0358','0346']%>
  </div>


                      </td>
     </tr>


     <tr>
              <td>
  <div class="field">
    <%= f.label :paraje %><br>
   <%= f.select :paraje, ['Rio Verde Arriba', 'Rio Verde Abajo','Arrollo Hondo Arriba','Manga Larga','Naranjal','Mirador','Pueblo Viejo','Bonagua','Romero','La Vereda','La Rosa','La Lima']%>
  </div>


                      </td>
     </tr>

     <tr>
              <td>
    <div class="field">
    <%= f.label :edad %><br>
    <%= f.text_field :edad %>
  </div>


                      </td>
     </tr>
 <tr>
              <td>
<div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>


                      </td>
     </tr>

     <tr>
              <td>
<div class="field">
    <%= f.label :sexo %><br>
   <%= f.select :sexo, ['M', 'F']%>
  </div>

                      </td>
     </tr>
      <tr>
              <td>
<div class="field">
    <%= f.label :fecha_ultimo_contacto %><br>
    <%= f.date_select :fecha_ultimo_contacto %>
  </div>



                      </td>
     </tr>

      <tr>
              <td>
<div class="field">
    <%= f.label :intencion %><br>
    <%= f.check_box :intesion %>
  </div>

    </td>
     </tr>


<tr>
              <td>
  <div class="actions">
    <%= f.submit %>
  </div>

</td>
 <td>
     <%= link_to 'Volver', @enc_contacto %>
    </td>

      </tr>

    </tbody>
</table>

  <% end %>

app/views/contactos/new.html.erb
<h3>Agregar un Contacto</h3>

<p id="notice"><%= notice %></p>
<%= form_for(@contacto, url: "/enc_contactos/#{@enc_contacto.id}/contactos/#{@contacto.id}" , html: {method: "post"}) do |f| %>

<table>
  <thead>
     <tr>
 <td>

  <% if @contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contacto.errors.count, "error") %> prohibited this enc_contacto from being saved:</h2>

      <ul>
      <% @contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


         </td></tr>
</thead>


  <tbody>

          <tr>
              <td>
               <div class="field">
                <%= f.label :nombre %><br>
                <%= f.text_field :nombre %>
              </div>
            </td>
      </tr>


            <tr>
              <td>
                  <div class="field">
                    <%= f.label :apellido %><br>
                    <%= f.text_field :apellido %>
                  </div>
                </td>
            </tr>

       <tr>
              <td>
                      <div class="field">
                    <%= f.label :cedula %><br>
                    <%= f.text_field :cedula %>
                  </div>

                       </td>
            </tr>

 <tr>
              <td>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>

      </td>
            </tr>

   <tr>
              <td>

  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
       </td>
            </tr>

       <tr>
              <td>

  <div class="field">
    <%= f.label :mesa %><br>
     <%= f.select :mesa, ['0069', '069A','0252','0307','0226','0325','0073','0074','0077','0075','0076','0271','0072','0225','0306','065A','0065','0070','0224','0308','0067','0068','068A','0066','0071','0079','0078','0081','080A','0080','0082','0083','0358','0346']%>
  </div>

                    </td>
            </tr>


       <tr>
              <td>
  <div class="field">
    <%= f.label :paraje %><br>
   <%= f.select :paraje, ['Rio Verde Arriba', 'Rio Verde Abajo','Arrollo Hondo Arriba','Manga Larga','Naranjal','Mirador','Pueblo Viejo','Bonagua','Romero','La Vereda','La Rosa','La Lima']%>
  </div>
 </td>
            </tr>

    <tr>
              <td>
    <div class="field">
    <%= f.label :edad %><br>
    <%= f.text_field :edad %>
  </div>

                  </td>
            </tr>

      <tr>
              <td>
<div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

                   </td>
            </tr>
 <tr>
              <td>
<div class="field">
    <%= f.label :sexo %><br>
    <%= f.select :sexo, ['M', 'F']%>
  </div>

                   </td>
            </tr>
    <tr>
              <td>
<div class="field">
    <%= f.label :fecha_ultimo_contacto %><br>
    <%= f.date_select :fecha_ultimo_contacto %>
  </div>

                   </td>
            </tr>
    <tr>
              <td>
<div class="field">
    <%= f.label :intencion %><br>
    <%= f.check_box :intesion %>
  </div>

                   </td>
            </tr>
<tr>
              <td>
  <div class="actions">
    <%= f.submit %>
                  </div></td>
 <td>
     <%= link_to 'Volver', @enc_contacto %>
    </td>

      </tr>

    </tbody>
</table>
 <% end %>

app/views/enc_contactos/_form.html.erb
<%= form_for(@enc_contacto) do |f| %>


<table>
  <thead>
     <tr>

         <td>Formulario: <% if @enc_contacto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enc_contacto.errors.count, "Falla") %> estas impiden que el nuevo encargado de contacto sea creado:</h2>

      <ul>
      <% @enc_contacto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      </td></tr>
    </thead>


    <tbody>

          <tr>
              <td>
                    <div class="field">
                        <%= f.label :nombre %><br>
                        <%= f.text_field :nombre ,size: 15 %>
                    </div>
                </td>
        </tr>




        <tr>
            <td>
                <div class="field">
                    <%= f.label :apellido %><br>
                    <%= f.text_field :apellido %>
                </div>
            </td>
        </tr>


        <tr>
            <td>
                <div class="field">
                    <%= f.label :telefono %><br>
                    <%= f.text_field :telefono %>
                </div>
            </td>
        </tr>





        <tr>
            <td>
                <div class="field">
                    <%= f.label :mesa %><br>
                    <%= f.select :mesa, ['0069', '069A','0252','0307','0226','0325','0073','0074','0077','0075','0076','0271','0072','0225','0306','065A','0065','0070','0224','0308','0067','0068','068A','0066','0071','0079','0078','0081','080A','0080','0082','0083','0358','0346']%>

                </div>
            </td>
        </tr>

         <tr>
             <td>
                 <div class="field">
                    <%= f.label :cedula %><br>
                    <%= f.text_field :cedula %>
                </div>
            </td>
        </tr>

            <tr>
                <td>
                    <div class="field">
                        <%= f.label :paraje %><br>

                        <%= f.select :paraje, ['Rio Verde Arriba', 'Rio Verde Abajo','Arrollo Hondo Arriba','Manga Larga','Naranjal','Mirador','Pueblo Viejo','Bonagua','Romero','La Vereda','La Rosa','La Lima']%>
                    </div>
                </td>
            </tr>

        <tr>
            <td>
                <div class="field">
                    <%= f.label :celular %><br>
                    <%= f.text_field :celular %>
                </div>
            </td>
        </tr>


        <tr>
            <td>
                <div class="actions">
                    <%= f.submit %>
                </div>
            </td>

            <td>
                <%= link_to 'Volver a Encargados', enc_contactos_path %>
            </td>

        </tr>

    </tbody>
</table>













<% end %>

app/views/enc_contactos/edit.html.erb
<h3>Editar Coordinador</h3>
<p id="notice"><%= notice %></p>
<p id="error" ><font color= "red"><%= error %></font></p>
<%= render 'form' %>

app/views/enc_contactos/new.html.erb
<h3>Nuevo Coordinador</h3>

<p id="notice"><%= notice %></p>
<p id="error" ><font color= "red"><%= error %></font></p>

<%= render 'form' %>

app/views/enc_contactos/show.html.erb
<h3> Coordinador </h3>

<p id="notice"><%= notice %></p>
<p id="error" ><font color= "red"><%= error %></font></p>
<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Cedula</th>
      <th>Celular</th>
      <th>Telefono</th>
      <th>Mesa</th>
      <th>Paraje</th>

    </tr>
  </thead>

  <tbody>

      <tr>
        <td><%= @enc_contacto.nombre %></td>
        <td><%= @enc_contacto.apellido %></td>
        <td><%= @enc_contacto.cedula %></td>
        <td><%= @enc_contacto.celular %></td>
        <td><%= @enc_contacto.telefono %></td>
        <td><%= @enc_contacto.mesa %></td>
        <td><%= @enc_contacto.paraje %></td>

      </tr>

  </tbody>
</table>

<div> <h3>Contactos por Coordinador 2016:</h3>

    <%= column_chart @enc_contacto.contactos.group(:mesa,:paraje ).count%>
          </div>

<h3>Contactos</h3>
<% i=0%>
<table>
  <thead>
    <tr>
    <th>#</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Cedula</th>
      <th>Celular</th>
      <th>Telefono</th>
      <th>Mesa</th>
      <th>Paraje</th>
        <th>Sexo</th>
        <th>Intencion</th>
        <th>Fecha de ultimo contacto</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enc_contacto.contactos.each do |contacto| %>
      <%if contacto.id != nil%>
      <tr>

        <td><%= i=i+1 %></td>
        <td><%= contacto.nombre %></td>
        <td><%= contacto.apellido %></td>
        <td><%= contacto.cedula %></td>
        <td><%= contacto.celular %></td>
        <td><%= contacto.telefono %></td>
        <td><%= contacto.mesa %></td>
          <td><%= contacto.paraje %></td>
          <td><%= contacto.sexo %></td>
          <td><%= contacto.intesion %></td>
        <td><%= contacto.fecha_ultimo_contacto %></td>
          <td><%= link_to 'Editar', "/enc_contactos/#{@enc_contacto.id}/contactos/#{contacto.id}/edit" %></td>
          <td><%= link_to 'Borrar', "/enc_contactos/#{@enc_contacto.id}/contactos/#{contacto.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <% end %>

    <% end %>
      <tr><td><%= link_to 'Agregar nuevo', "/enc_contactos/#{@enc_contacto.id}/contactos/new" %></td>
          <td><%= link_to 'Volver a Encargados', enc_contactos_path %></td>
      </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Politica</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

</head>
<body >




<div class="wrapper">
			<div class="content">

				<div id="form_wrapper" class="form_wrapper">

                    <img src="/images/EQUIPO3.png" alt="Equipo3" />
                        <div class="boxview">

                                        <%= yield %>

                            <div class="bottom">
<p >Partido de la Liberacion Dominicana (PLD) Distrito Municipal De Rio Verde, La Vega, Rep. Dom.</p>
							<div class="clear"> </div>

</div>
                        		</div>

</div>

				<div class="clear"></div>
			</div>


		</div>
</body>
</html>